version: '3'
services:
  "webapp":
    build: "./webapp"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./webapp/src:/webapp/src"
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase

  redis:
    build: ./redis
    ports:
      - '6767:6767'
  
  nginx:
    build: ./nginx 
    volumes:
      - "./nginx/public:/usr/share/nginx/html"
    ports:
     - "3000:80"
    